### ISSUE TITLE
issue 101 -'getk1' is not defined - I fixed it 🥇 

### ISSUE THREAD

**Issue by RedWilly** [harshjamdar/RSZ-Scanner#1]
Duplicate R Found. Congrats!. (103, 105, '0400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000')
======================================================================
------------------------------------------------------------------------------------------------------------------------
Starting to prepare BSGS Table with 5671 elements
Traceback (most recent call last):
  File "C:\Users\Redwilly\Desktop\DEX\zzbtcz\RSZ-Scanner\main.py", line 206, in <module>
    main(args.file)
  File "C:\Users\Redwilly\Desktop\DEX\zzbtcz\RSZ-Scanner\main.py", line 197, in main
    private_keys = get_private_keys(rL, sL, zL, solvable_diff)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\Desktop\DEX\zzbtcz\RSZ-Scanner\main.py", line 168, in get_private_keys
    k = getk1(rL[i[0]], sL[i[0]], zL[i[0]], rL[i[1]], sL[i[1]], zL[i[1]], int(i[2], 16))
        ^^^^^
NameError: name 'getk1' is not defined

**Comment by RedWilly** [comment]
Solution add this in to code>

```
def getk1(r1, s1, z1, r2, s2, z2, diff):
    return ((z1 * s2 - z2 * s1) * inv(r1 * (s1 - s2))) % N

def getpvk(r1, s1, z1, r2, s2, z2, diff):
    return ((z1 * s2 - z2 * s1) * inv(r1 * (s1 - s2)) + diff) % N

```

should fix it.

**Comment by Vladimir855** [comment]
> Решение добавьте это в код>
> 
> ```
> def getk1(r1, s1, z1, r2, s2, z2, diff):
>     return ((z1 * s2 - z2 * s1) * inv(r1 * (s1 - s2))) % N
> 
> def getpvk(r1, s1, z1, r2, s2, z2, diff):
>     return ((z1 * s2 - z2 * s1) * inv(r1 * (s1 - s2)) + diff) % N
> ```
> 
> должно это исправить.

можешь сюда скинуть правильный скрипт с изменением

**Comment by harshjamdar** [comment]
please check code is updates in case of any issue feel free to  contact me at Harsh7744jamdar@gmail.com
